POST localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Muhammadjon",
  "username": "jmaxjj@naver.com",
  "password": "max"
}

###Login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "jmaxjj@naver.com",
  "password": "max"
}