POST localhost:8087/auth/register
Content-Type: application/json

{
  "name": "Max",
  "username": "ortigaliyevm@gmail.com",
  "password": "max"
}

###Login
POST localhost:8087/auth/login
Content-Type: application/json

{
  "username": "ortigaliyevm@gmail.com",
  "password": "1234"
}